fixtures:
  forge_modules:
    augeas_core: 'puppetlabs/augeas_core'
    augeasproviders_core: 'herculesteam/augeasproviders_core'
    augeasproviders_shellvar: 'herculesteam/augeasproviders_shellvar'
    stdlib: 'puppetlabs/stdlib'
  repositories:
    # litmus dependencies
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    openldap: "#{source_dir}"
