---
.travis.yml:
  addons:
    apt:
      sources:
        - augeas
      packages:
        - libaugeas-dev
  acceptance:
    - '*'
  docker_sets:
    -
      set: ''
      collection: puppet5
      options:
        env: "PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=@@COLLECTION@@ BEAKER_set=@@SET@@ BEAKER_setfile=centos6-64{hypervisor=docker} BEAKER_TESTMODE=@@TESTMODE@@"
    -
      set: ''
      collection: puppet5
      options:
        env: "PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=@@COLLECTION@@ BEAKER_set=@@SET@@ BEAKER_setfile=centos7-64{hypervisor=docker} BEAKER_TESTMODE=@@TESTMODE@@"
    -
      set: ''
      collection: puppet5
      options:
        env: "PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=@@COLLECTION@@ BEAKER_set=@@SET@@ BEAKER_setfile=debian8-64{hypervisor=docker} BEAKER_TESTMODE=@@TESTMODE@@"
    -
      set: ''
      collection: puppet5
      options:
        env: "PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=@@COLLECTION@@ BEAKER_set=@@SET@@ BEAKER_setfile=debian9-64{hypervisor=docker} BEAKER_TESTMODE=@@TESTMODE@@"
    -
      set: ''
      collection: puppet5
      options:
        env: "PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=@@COLLECTION@@ BEAKER_set=@@SET@@ BEAKER_setfile=ubuntu1604-64{hypervisor=docker} BEAKER_TESTMODE=@@TESTMODE@@"
    -
      set: ''
      collection: puppet5
      options:
        env: "PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=@@COLLECTION@@ BEAKER_set=@@SET@@ BEAKER_setfile=ubuntu1804-64{hypervisor=docker} BEAKER_TESTMODE=@@TESTMODE@@"
  forge_password: "ZjmgM4a2tcCE4dtccVSmYZAcuCaXdZNsZxVzRiDg7URBYyALMNgCV6XaiS/DTHX4jCuiyw/89Vywyf+uDjrj1552D+lF3cuQMXziwJhXp9v0jJRT9kpq8CFnq4iC/qwqLj54QIhIFoVgtiY9k+2MWRoMuGveLnAmg9K6wSNvLS4="

Gemfile:
  required:
    ':development':
      - gem: ruby-augeas

spec/spec_helper.rb:
  spec_overrides:
    - |-
      require 'pathname'
      dir = Pathname.new(__FILE__).parent
      Puppet[:modulepath] = File.join(dir, 'fixtures', 'modules')

      # There's no real need to make this version dependent, but it helps find
      # regressions in Puppet
      #
      # 1. Workaround for issue #16277 where default settings aren't initialised from
      # a spec and so the libdir is never initialised (3.0.x)
      # 2. Workaround for 2.7.20 that now only loads types for the current node
      # environment (#13858) so Puppet[:modulepath] seems to get ignored
      # 3. Workaround for 3.5 where context hasn't been configured yet,
      # ticket https://tickets.puppetlabs.com/browse/MODULES-823
      #
      ver = Gem::Version.new(Puppet.version.split('-').first)
      if Gem::Requirement.new('~> 2.7.20') =~ ver || Gem::Requirement.new('~> 3.0.0') =~ ver || Gem::Requirement.new('~> 3.5') =~ ver || Gem::Requirement.new('~> 4.0')
        puts 'augeasproviders: setting Puppet[:libdir] to work around broken type autoloading'
        # libdir is only a single dir, so it can only workaround loading of one external module
        Puppet[:libdir] = "#{Puppet[:modulepath]}/augeasproviders_core/lib"
      end

.rubocop.yml:
  selected_profile: cleanups_only

